"""
Edge-case tests that probe for subtle bugs in the implementation:
- Delete + undo restoring track position
- InsertClipOperation with missing clip_id (auto-generated UUID)
- Multiple tracks
- Serializer roundtrip with entities (Clip inside entities map)
- DeleteEntity on non-existent entity (no-op)
- insert_clip missing payload fields
"""
import pytest

from core.domain.assets import AssetRegistry, ExternalFileReference
from core.domain.entities import Clip, Track
from core.domain.state import EditGraphState
from core.domain.time import RationalTime, TimeRange
from core.engine import EditEngine
from core.ops.builtin_timeline_ops import (
    DeleteEntityOperation,
    InsertClipOperation,
    RestoreEntityOperation,
    TrimClipOperation,
)
from core.ops.validator import OperationValidator


def mk_state(media_ref_id="media-1"):
    registry = AssetRegistry()
    media = ExternalFileReference(
        file_path="./media/a.mp4", format_hint="mp4",
        available_range=TimeRange(RationalTime(0, 25), RationalTime(500, 25)),
    )
    media.ref_id = media_ref_id
    registry.register(media)
    track = Track(id="track-1", kind="track", schema_version="1.0.0",
                  track_type="video", item_ids=[], name="V1")
    return EditGraphState(
        project_meta={"name": "test"}, tracks=[track],
        entities={}, asset_registry=registry, schema_version="1.0.0",
    )


class TestDeleteAndUndoRestoresPosition:
    """After delete+undo, the clip should return to its exact position in the track."""

    def test_delete_undo_restores_track_position(self):
        state = mk_state()
        engine = EditEngine()
        media_id = "media-1"
        for i, cid in enumerate(["c1", "c2", "c3"]):
            op = InsertClipOperation(
                op_type="insert_clip", actor="ai",
                payload={
                    "track_id": "track-1", "position": i,
                    "media_ref_id": media_id,
                    "source_in": {"value": 0, "rate": 25},
                    "source_out": {"value": 50, "rate": 25},
                    "clip_id": cid,
                },
            )
            engine.apply(op, state)
        assert state.tracks[0].item_ids == ["c1", "c2", "c3"]

        del_op = DeleteEntityOperation(
            op_type="delete_entity", actor="ai",
            payload={"entity_id": "c2"},
        )
        engine.apply(del_op, state)
        assert state.tracks[0].item_ids == ["c1", "c3"]
        assert "c2" not in state.entities

        engine.undo(state)
        assert "c2" in state.entities
        assert state.tracks[0].item_ids == ["c1", "c2", "c3"]


class TestInsertAutoGeneratedClipId:
    def test_auto_id_when_clip_id_not_in_payload(self):
        state = mk_state()
        op = InsertClipOperation(
            op_type="insert_clip", actor="ai",
            payload={
                "track_id": "track-1", "position": 0,
                "media_ref_id": "media-1",
                "source_in": {"value": 0, "rate": 25},
                "source_out": {"value": 100, "rate": 25},
            },
        )
        delta = op.apply(state)
        assert len(state.entities) == 1
        assert len(delta.added) == 1


class TestDeleteNonExistentEntity:
    def test_delete_missing_entity_is_noop(self):
        state = mk_state()
        op = DeleteEntityOperation(
            op_type="delete_entity", actor="ai",
            payload={"entity_id": "ghost"},
        )
        delta = op.apply(state)
        assert delta.removed == []


class TestInsertClipValidation:
    def test_missing_required_fields_rejected(self):
        state = mk_state()
        op = InsertClipOperation(
            op_type="insert_clip", actor="ai",
            payload={"track_id": "track-1"},
        )
        result = op.validate(state)
        assert not result.ok

    def test_source_in_before_available_range_rejected(self):
        state = mk_state()
        op = InsertClipOperation(
            op_type="insert_clip", actor="ai",
            payload={
                "track_id": "track-1", "position": 0,
                "media_ref_id": "media-1",
                "source_in": {"value": -10, "rate": 25},
                "source_out": {"value": 100, "rate": 25},
                "clip_id": "clip-bad",
            },
        )
        v = OperationValidator()
        result = v.validate(op, state)
        assert not result.ok
        assert "before available range" in result.reason

    def test_source_rate_mismatch_rejected(self):
        state = mk_state()
        op = InsertClipOperation(
            op_type="insert_clip", actor="ai",
            payload={
                "track_id": "track-1", "position": 0,
                "media_ref_id": "media-1",
                "source_in": {"value": 0, "rate": 25},
                "source_out": {"value": 100, "rate": 30},
                "clip_id": "clip-bad",
            },
        )
        v = OperationValidator()
        result = v.validate(op, state)
        assert not result.ok


class TestMultipleTracks:
    def test_insert_into_second_track(self):
        state = mk_state()
        track2 = Track(id="track-2", kind="track", schema_version="1.0.0",
                       track_type="audio", item_ids=[], name="A1")
        state.tracks.append(track2)
        engine = EditEngine()
        op = InsertClipOperation(
            op_type="insert_clip", actor="ai",
            payload={
                "track_id": "track-2", "position": 0,
                "media_ref_id": "media-1",
                "source_in": {"value": 0, "rate": 25},
                "source_out": {"value": 50, "rate": 25},
                "clip_id": "audio-clip",
            },
        )
        engine.apply(op, state)
        assert state.tracks[0].item_ids == []
        assert state.tracks[1].item_ids == ["audio-clip"]


class TestStateHashConsistency:
    def test_hash_same_after_json_roundtrip(self):
        from core.serialization.serializer import StateSerializer

        state = mk_state()
        engine = EditEngine()
        op = InsertClipOperation(
            op_type="insert_clip", actor="ai",
            payload={
                "track_id": "track-1", "position": 0,
                "media_ref_id": "media-1",
                "source_in": {"value": 0, "rate": 25},
                "source_out": {"value": 100, "rate": 25},
                "clip_id": "clip-1",
            },
        )
        engine.apply(op, state)
        h1 = state.state_hash
        serializer = StateSerializer()
        json_str = serializer.to_json(state)
        restored = serializer.from_json(json_str)
        h2 = restored.state_hash
        assert h1 == h2


class TestRestoreEntityOperation:
    def test_restore_only_supports_clip_v1(self):
        state = mk_state()
        op = RestoreEntityOperation(
            op_type="restore_entity", actor="ai",
            payload={
                "entity": {
                    "id": "gap-1", "kind": "gap",
                    "schema_version": "1.0.0", "attributes": {},
                    "enabled": True, "duration": {"value": 100, "rate": 25},
                },
            },
        )
        with pytest.raises(ValueError, match="Only clip restore"):
            op.apply(state)
